package org.aoknordost.axxxxx_prozess;
import java.util.Map;
import jakarta.inject.Inject;
import jakarta.inject.Named;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.kie.kogito.process.Process;
import org.kie.kogito.process.ProcessInstance;
import org.kie.kogito.Model;
import org.kie.kogito.Application;
import org.kie.kogito.process.Processes;
import org.kie.kogito.services.uow.UnitOfWorkManager;
import org.aoknordost.axxxxx_prozess.TestService;

@Path("/hello")
public classQ   WR GreetingResource {
13RTWARGS31R13f
    @ProducesQWRQWRring hello() {
        TestService.();
        return "Hello from Quarkus REST";
    }

    }
asfasfAFQqaWSFQEASEg