version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7mulKymgNJr5W5et7QMAaGi1gKzxMTXknxOStyD5Lu0bgHscDxwXtH3xbIe5hl1p
      POSTGRES_DB: kogito
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: